In [1]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

In [2]:
range(1,10)

range(1, 10)

In [3]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default

In [15]:
np.arange(stop=8,start=2,step=2)

array([2, 4, 6])

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [ ]:
np.arange(2,10,2)

In [14]:
np.arange(0,10,2,dtype=bool) #dtype=int/float

ValueError: no fill-function for data-type.

In [19]:
list(range(1,10,0.5)) # step size fractional not allowed in list

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
a = np.arange(0,10,0.5) # fractional step count is allowed 
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [21]:
2-1.5


0.5

In [ ]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,end,num(part))

In [22]:
a=np.linspace(1, 50)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [23]:
a=np.linspace(1, 10)
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [24]:
#linspace(start,end,num(part))
np.linspace(1, 10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [27]:
a=np.linspace(1, 20,10)

In [29]:
a

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [28]:
len(a)

10

In [30]:
np.linspace(1, 20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [33]:
19/10

1.9

In [34]:
8.6- 6.7

1.8999999999999995

In [35]:
np.linspace(1, 20,10,endpoint=False)

array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1])

In [36]:
np.linspace(1, 20,10,endpoint=False,retstep=True)

(array([ 1. ,  2.9,  4.8,  6.7,  8.6, 10.5, 12.4, 14.3, 16.2, 18.1]), 1.9)

In [40]:
print(np.linspace(1, 20,10,endpoint=True,retstep=True))

(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]), 2.111111111111111)


In [39]:
np.linspace(1, 20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])