# Numpy


In [ ]:
# pip install numpy # For installation
# Syntax : pip install <package_name>  ==>used to install a package from the Python Package Index (PyPI) or other package repositories.
# pip: package manager for Python that allows users to install and manage software packages written in Python.

In [1]:
import numpy as np  #import numpy

# import            numpy             as   np   
# keyword     library/modules name        alias 

In [ ]:
# import numpy

In [4]:
# numpy.array([1,2,3])

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
L=list(range(1,11))

In [6]:
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [7]:
len(L)

10

In [8]:
type(L)

list

In [9]:
# Create a 1D array
a=np.array(L)

In [10]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
len(a)

10

In [12]:
type(a)

numpy.ndarray

In [14]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [13]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
L+2

TypeError: can only concatenate list (not "int") to list

In [25]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#element-wise operations with lists require a bunch of code

In [18]:
for i in L:
    print(i+2, end=" ,")

3 ,4 ,5 ,6 ,7 ,8 ,9 ,10 ,11 ,12 ,

In [ ]:
map(fun,iterable)

In [22]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [23]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
list(map(lambda x:x+2,L))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [26]:
L-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [27]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [29]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
L*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [30]:
L*0.5

TypeError: can't multiply sequence by non-int of type 'float'

In [31]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
a*0.5

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

In [33]:
L

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [35]:
L2=[1, 2, 3, 4, "5", 6, 7, 8, 9, 10]

In [36]:
L2

[1, 2, 3, 4, '5', 6, 7, 8, 9, 10]

In [39]:
type(L2[0])

int

In [40]:
L2[4]

'5'

In [41]:
type(L2[4])

str

In [42]:
a2=np.array(L2)

In [44]:
L2

[1, 2, 3, 4, '5', 6, 7, 8, 9, 10]

In [43]:
print(a2)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [ ]:
np.array(L,dtype=str)

In [ ]:
# Index / Mutability

In [45]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#       0   1   2  3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [ ]:
#6

In [46]:
a[5]

6

In [ ]:
#Reverse

In [55]:
a[10::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [56]:
a[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# variable  [start :       end :              step]
#           0         len(variable)          1

In [49]:
# 8,7,6  
a[-3:-6:-1]

array([8, 7, 6])

In [57]:
a[7:4:-1]

array([8, 7, 6])