In [1]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

In [2]:
[2,3,"one",4.5]

[2, 3, 'one', 4.5]

In [3]:
np.array([2,3,"one",4.5])

array(['2', '3', 'one', '4.5'], dtype='<U32')

In [4]:
L=[1, 2, 3, 4, 5, "6", 7, 8, 9, 10]

In [5]:
L

[1, 2, 3, 4, 5, '6', 7, 8, 9, 10]

In [6]:
np.array(L)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

In [ ]:
# dtype

In [7]:
np.array(L,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.array(L,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.array(L,dtype=str)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

In [ ]:
# Index / Mutability

In [ ]:
# Indexing/Slicing Homework

In [10]:
a=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [11]:
#       0   1   2  3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [12]:
# variable  [start :       end :              step]
#           0         len(variable)          1      Default value

In [13]:
a[0] #first element at index position 0 

1

In [14]:
a[1] #second element (index position 1)

2

In [15]:
a[-1] #last element

10

In [16]:
a[2:6] #slicing from index position 2 (incl.) till position 6 (excl.) 

array([3, 4, 5, 6])

In [ ]:
#       0   1   2   3    4   5   6   7   8   9    ==> Positive Index
#     [ 1   2   3   4   5   6   7   8   9   10]  ==> Left to right
#     -10  -9  -8  -7  -6  -5  -4  -3  -2   -1   ==> Negative Index

In [17]:
a[:] #all elements

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a[:5] #all elements until index position 5 (excl.)

array([1, 2, 3, 4, 5])

In [19]:
a[6:] #all elements from index position 6 (incl.) till the last element (incl.)

array([ 7,  8,  9, 10])

In [20]:
a[::2] #every second element, starting from first element

array([1, 3, 5, 7, 9])

In [21]:
a[::3] #every third element, starting from first element

array([ 1,  4,  7, 10])

In [22]:
a[2::3] #every third element, starting from third element (index position 2)

array([3, 6, 9])

In [23]:
a[0]

1

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a[0] = 100 #ndarrays are mutable, changing first element to 100 

In [26]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [27]:
a[-1] = 101 #changing last element to 101

In [28]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [29]:
a[::-1]  #Reverse

array([101,   9,   8,   7,   6,   5,   4,   3,   2, 100])

In [31]:
# 8,7,6  
a[-3:-6:-1]

array([8, 7, 6])

In [32]:
a[7:4:-1]

array([8, 7, 6])

In [30]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [34]:
#arrays is iterable
for i in a: # same as lists, ndarrays store multiple elements (is iterable) 
    print(i,end=" ,")

100 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,101 ,

In [35]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [36]:
a.shape #array shape :tuple representing the dimensions of the array

(10,)

In [37]:
a.ndim  # dimension

1

In [38]:
a.size  # no. arry elements

10

In [39]:
len(a)

10

In [41]:
a

array([100,   2,   3,   4,   5,   6,   7,   8,   9, 101])

In [40]:
a.dtype #data type of array element (int,float,complex,bool,string,object)

dtype('int32')

In [ ]:
#Change datatype

In [42]:
L

[1, 2, 3, 4, 5, '6', 7, 8, 9, 10]

In [43]:
a=np.array(L,dtype=str)

In [44]:
a

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

In [ ]:
# astype
# Array.astype(datatype)

In [45]:
a.astype(float) #change data type

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
a.astype(int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
a.astype(str)

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U2')

In [48]:
a.astype(complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,
        8.+0.j,  9.+0.j, 10.+0.j])

In [50]:
a=np.array([1,2,3,0])

In [51]:
a.astype(bool)

array([ True,  True,  True, False])