# Numpy


In [4]:
import numpy as np   # call
#      library  alias

In [7]:
# Create a 1D array
a = np.array([1, 2, 3])

In [8]:
print(a)

[1 2 3]


In [11]:
type(a)

numpy.ndarray

In [9]:
z = [1,2,3,4,5,6,7,8,9]

In [10]:
print(z)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
print(type(z))

<class 'list'>


In [13]:
list_a=[1,2,3,4]
tuple_a=(1,2,3,4,5)

In [14]:
list_a

[1, 2, 3, 4]

In [15]:
tuple_a

(1, 2, 3, 4, 5)

In [24]:
type(np.array(list_a))

numpy.ndarray

In [23]:
type(np.array(tuple_a))

numpy.ndarray

In [26]:
list_a

[1, 2, 3, 4]

In [29]:
list_a+2

TypeError: can only concatenate list (not "int") to list

In [30]:
list_a-2

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [27]:
list_a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [28]:
list_a*0.5

TypeError: can't multiply sequence by non-int of type 'float'

In [31]:
list_a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [32]:
list_a**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [42]:
list_a+list_a

[1, 2, 3, 4, 1, 2, 3, 4]

In [33]:
Array=np.array([1, 2, 3])

In [35]:
print(Array)

[1 2 3]


In [36]:
add=c

In [37]:
print(add)

[3 4 5]


In [38]:
Array-1

array([0, 1, 2])

In [39]:
Array*2

array([2, 4, 6])

In [41]:
Array**2

array([1, 4, 9])

In [40]:
Array/2

array([0.5, 1. , 1.5])

In [45]:
print(Array)

[1 2 3]


In [43]:
Array+Array

array([2, 4, 6])

In [46]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [49]:
np.array([[1,2,3,4,5],[1,2,3,4,5]])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [52]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [53]:
b=np.array([[1,2,3,4,5],[4,2,3,4,5],[3,2,3,4,5]])

In [54]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [55]:
b

array([[1, 2, 3, 4, 5],
       [4, 2, 3, 4, 5],
       [3, 2, 3, 4, 5]])

In [56]:
a+b

array([[ 2,  4,  6,  8, 10],
       [ 5,  4,  6,  8, 10],
       [ 4,  4,  6,  8, 10]])

In [ ]:
np.array([1, 2, 3])

In [19]:
# a=4
# b=3
# a+b

In [18]:
a

array([1, 2, 3])