In [3]:
import numpy as np   

In [ ]:
# pip install numpy

In [4]:
#1D array
a=np.array([1,2,3,4,5])

In [35]:
a

array([1, 2, 3, 4, 5])

In [5]:
print(a)

[1 2 3 4 5]


In [8]:
b = np.array([[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8,9]])

In [10]:
c = np.array([[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8]])

C:\Users\Prajakta\AppData\Local\Temp/ipykernel_15752/3024718243.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c = np.array([[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8]])


In [12]:
print(c)

[list([1, 2, 3, 4, 5, 6, 7, 8, 9]) list([1, 2, 3, 4, 5, 6, 7, 8])]


In [13]:
c.shape

(2,)

In [14]:
print(a)

[1 2 3 4 5]


In [15]:
print(b)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [21]:
c=np.array([[1,2,3,4],[4,5,6,4],[7,8,9,4]])

In [22]:
print(c)

[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]


In [31]:
d=np.array([[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])

In [33]:
print(d)

[[[1 2 3 4]
  [4 5 6 4]
  [7 8 9 4]]]


In [36]:
d=np.array([[[1,2,3,4],[4,5,6,4],[7,8,9,4]],[[1,2,3,4],[4,5,6,4],[7,8,9,4]]])

In [30]:
d

array([[[1, 2, 3, 4],
        [4, 5, 6, 4],
        [7, 8, 9, 4]],

       [[1, 2, 3, 4],
        [4, 5, 6, 4],
        [7, 8, 9, 4]]])

In [ ]:
# shape:number of elements in each dimension.==>(rows,columns)

In [16]:
# Get the shape of an array
print(a.shape) 

(5,)


In [17]:
b.shape  # rows,columns

(2, 9)

In [23]:
c.shape

(3, 4)

In [24]:
# Get the number of dimensions of an array
print(a.ndim)

1


In [25]:
b.ndim

2

In [26]:
c.ndim

2

In [37]:
d.ndim

3

In [ ]:
# arange: Returns an array with evenly spaced elements as per the interval
# arange(start, stop, step)

In [38]:
# Creating arrays

# 1D array
a1 = np.arange(15) # same as range 
print(a1)
print(type(a1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [39]:
a = np.arange(15,25)
print(a)

[15 16 17 18 19 20 21 22 23 24]


In [41]:
a = np.arange(0,10,1,int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# np.arange(start,stop,stepsize)
a = np.arange(0,100,5,int)
print(a)

In [ ]:
a = np.arange(0,100,10)
print(a)

In [42]:
a = list(range(0,10,0.5))
print(a)

TypeError: 'float' object cannot be interpreted as an integer

In [43]:
a = np.arange(0,10,0.5) # fractional step count is allowed 
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [44]:
type(a)

numpy.ndarray

In [ ]:
# reshape to convert the array dimension
# 2D array

In [45]:
a = np.arange(15)

In [47]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [48]:
a = np.arange(18).reshape(3,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [49]:
a = np.arange(15).reshape(3,6)
print(a)

ValueError: cannot reshape array of size 15 into shape (3,6)

In [50]:
a = np.arange(15).reshape(2,7)
print(a)

ValueError: cannot reshape array of size 15 into shape (2,7)

In [51]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [52]:
a = np.arange(16).reshape(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [53]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
