In [2]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

In [ ]:
# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default  # fractional step count is allowed 

In [ ]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(5,12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [4]:
np.arange(5,12,10)

array([5])

In [12]:
# Creating 1D array: Excel (perticular column only)

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# Creating  2D array: Excel (Row and columns)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Creating  3D array: Image

arr3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
[1,2,3,[1,2,3[1,2,3]],1,2,3]
        3     3

In [ ]:
[3][3]

In [18]:
np.array([[[1, 2, 3], [4, 5, 6],[4, 5, 6]],
          [[1, 2, 3], [4, 5, 6],[4, 5, 6]]]).shape

(2, 3, 3)

In [13]:
arr.shape

(5,)

In [14]:
arr2d.shape #array shape :tuple representing the dimensions of the array

(2, 3)

In [15]:
arr3d.shape

(1, 2, 3)

In [1]:
arr2d.ndim  # dimension

NameError: name 'arr2d' is not defined

In [5]:
arr2d.size  # no. arry elements

6

In [6]:
arr2d.dtype #data type of array element (int,float,complex,bool,string,object)

dtype('int32')