### Indexing and slicing NumPy arrays:

In [102]:
import numpy as np

In [103]:
arr=np.arange(1,11)

In [104]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr[0]

1

In [106]:
arr[1:4]

array([2, 3, 4])

In [107]:
arr[1:4:2]

array([2, 4])

In [108]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Indexing and Slicing multi-dimensional arrays

In [111]:
import numpy as np

In [112]:
arr=np.arange(2,42,2)

In [113]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [114]:
arr.size

20

In [115]:
b=arr.reshape(4,5)

In [116]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [ ]:
print(b)

In [ ]:
#             -5 -4  -3 -2 -1
# Rows Columns 0  1  2  3  4  
#    0      [[ 2  4  6  8 10]
#    1       [12 14 16 18 20]
#    2       [22 24 26 28 30]
#    3       [32 34 36 38 40]]

In [135]:
b[: ,-1]

array([10, 20, 30, 40])

In [133]:
b[: : -1,-1]

array([40, 30, 20, 10])

In [140]:
b[4:0:-1 , -1]

array([40, 30, 20])

In [120]:
# Multiple dimension array: 2D
# M1) variable_name[row,column]
# M2) variable_name[row][column]

In [ ]:
# Multiple dimension array:3D
# M1) variable_name[Frame,row,column]
# M2) variable_name[Frame][row][column]

In [122]:
#36
# M1)
b[3,2]


36

In [123]:
#36
# M2)
b[3][2]

36

In [ ]:
# 6   8
# 16  18
b[0,2:4]

In [125]:
# 6  8
b[0:2,2:4]

b[0:2][2:4]

array([[ 6,  8],
       [16, 18]])

In [129]:
b[-1]

array([32, 34, 36, 38, 40])

In [130]:
b[:,-1]

array([10, 20, 30, 40])

In [128]:
b[: : -1,-1]

array([40, 30, 20, 10])

In [131]:
c=[10, 20, 30, 40]

In [132]:
c[: : -1]

[40, 30, 20, 10]

In [137]:
c[0:4 : -1]

[]

In [138]:
c[4: : -1]

[40, 30, 20, 10]

In [ ]:
# # Retrive following value from array b
# 1) 14
# 2) 28
# 3) 6
# 4) 34

# 5) 24,26,28

# 6) 14,16
#    24,26

# 7)[22, 24, 26, 28, 30]
#   [32, 34, 36, 38, 40]
    
# 8) 4
#    14
#     24
#     34

In [117]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [144]:
b[0] #first row (index position 0)

array([ 2,  4,  6,  8, 10])

In [145]:
b[1] #second row (index position 1)

array([12, 14, 16, 18, 20])

In [146]:
b[2] #third row (index position 2)

array([22, 24, 26, 28, 30])

In [147]:
b[-1] #last row (index position -1)

array([32, 34, 36, 38, 40])

In [148]:
b[1][1] #second row, second column

14

In [149]:
b[1,1] #more convenient in one square bracket

14

In [150]:
b[2,-1] #third row, last column

30

In [151]:
b[:,0] #all rows, first column

array([ 2, 12, 22, 32])

In [152]:
b[:,1] #all rows, second column

array([ 4, 14, 24, 34])

In [153]:
b[:,-1] #all rows, last column

array([10, 20, 30, 40])

In [154]:
b[:2,1:3] #first two rows, column two and three

array([[ 4,  6],
       [14, 16]])