## Create matrix with initial values

In [ ]:
# # Methods
# np.array()
# np.arange()
# np.linspace()

# # With initial values
# np.eye():Creates an identity matrix
# np.zeros:Creates an array filled with zeros
# np.ones():Creates an array filled with ones
# np.full():Creates an array filled with a specified value
# np.empty() : Create with random values

In [57]:
import numpy as np

In [58]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.ones((2,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [62]:
np.full((4, 6), 9)  

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [63]:
np.empty((4, 3))

array([[9.65439190e-312, 2.86558075e-322, 0.00000000e+000],
       [0.00000000e+000, 4.00766127e+175, 1.04082753e-047],
       [4.51137645e-090, 8.23585267e-067, 1.52373855e-052],
       [1.79747509e-052, 6.48224659e+170, 5.82471487e+257]])

In [64]:
b=np.arange(2,41,2)

In [65]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [66]:
b.size

20

In [67]:
b=b.reshape((5,4),order="F")

In [68]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [69]:
# Convert multi-dimensional arrays into one-dimensional arrays
# M1) ravel :returns a view of the original array. Changes to the new array may affect the original array and vice versa.
# M2) flatten :returns a copy of the original array. Changes to the new array do not affect the original array.
# M3) reshape

In [70]:
flatten_array=b.flatten()

In [71]:
ravel_array=b.ravel()

In [72]:
flatten_array

array([ 2, 12, 22, 32,  4, 14, 24, 34,  6, 16, 26, 36,  8, 18, 28, 38, 10,
       20, 30, 40])

In [73]:
ravel_array

array([ 2, 12, 22, 32,  4, 14, 24, 34,  6, 16, 26, 36,  8, 18, 28, 38, 10,
       20, 30, 40])

In [74]:
flatten_array[2]=222

In [75]:
flatten_array

array([  2,  12, 222,  32,   4,  14,  24,  34,   6,  16,  26,  36,   8,
        18,  28,  38,  10,  20,  30,  40])

In [76]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [77]:
b[1,1]

14

In [78]:
# Change 14 to 144
b[1,1]=144

In [79]:
b

array([[  2,  12,  22,  32],
       [  4, 144,  24,  34],
       [  6,  16,  26,  36],
       [  8,  18,  28,  38],
       [ 10,  20,  30,  40]])

In [80]:
# [[ 2, 12, 22, 32],
#  [ 4, 14, 24, 34],
#  [ 6, 16, 26, 36],
#  [ 8, 18, 28, 38],
#  [10, 20, 30, 40]]

In [81]:
flatten_array 

array([  2,  12, 222,  32,   4,  14,  24,  34,   6,  16,  26,  36,   8,
        18,  28,  38,  10,  20,  30,  40])

In [82]:
ravel_array

array([ 2, 12, 22, 32,  4, 14, 24, 34,  6, 16, 26, 36,  8, 18, 28, 38, 10,
       20, 30, 40])

In [83]:
# Change in ravel and observe original array

In [84]:
ravel_array[0]=200

In [85]:
ravel_array

array([200,  12,  22,  32,   4,  14,  24,  34,   6,  16,  26,  36,   8,
        18,  28,  38,  10,  20,  30,  40])

In [86]:
b

array([[  2,  12,  22,  32],
       [  4, 144,  24,  34],
       [  6,  16,  26,  36],
       [  8,  18,  28,  38],
       [ 10,  20,  30,  40]])

### Mathematical functions

In [87]:
import numpy as np

In [88]:
b=np.arange(2,41,2).reshape((5,4),order="F")

In [89]:
print(b)

[[ 2 12 22 32]
 [ 4 14 24 34]
 [ 6 16 26 36]
 [ 8 18 28 38]
 [10 20 30 40]]


In [90]:
b.sum() #sum over all elements in matrix

420

In [91]:
b.sum(axis = 0) #sum of each column

array([ 30,  80, 130, 180])

In [92]:
12+14+16+18+20

80

In [93]:
b.sum(axis = 1) #sum of each row

array([ 68,  76,  84,  92, 100])

In [94]:
 2 +12 +22+ 32

68

In [95]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [96]:
b.sum()

420

In [97]:
b.cumsum() #cumulative sum of all elements

array([  2,  14,  36,  68,  72,  86, 110, 144, 150, 166, 192, 228, 236,
       254, 282, 320, 330, 350, 380, 420])

In [98]:
b.cumsum(axis = 0) #cumulative sum for each column

array([[  2,  12,  22,  32],
       [  6,  26,  46,  66],
       [ 12,  42,  72, 102],
       [ 20,  60, 100, 140],
       [ 30,  80, 130, 180]])

In [99]:
b.cumsum(axis = 1) #cumulative sum for each row

array([[  2,  14,  36,  68],
       [  4,  18,  42,  76],
       [  6,  22,  48,  84],
       [  8,  26,  54,  92],
       [ 10,  30,  60, 100]])

In [100]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [15]:
b.max() #maximum 

40

In [16]:
b.max(axis=0) #maximum 

array([10, 20, 30, 40])

In [17]:
b.max(axis=1) #maximum 

array([32, 34, 36, 38, 40])

In [20]:
b.min() #minimum 

2

In [21]:
b.mean() #mean 

21.0

In [22]:
np.median(b) #median

21.0

In [23]:
b.std() #standard deviation

11.532562594670797

In [24]:
b.var() #variance

133.0

In [28]:
np.percentile(b, 10) #10th percentile

5.800000000000001

In [30]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [ ]:
100 ==> 50th
21 ==>  11th

In [32]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [35]:
cc=b.flatten()

In [36]:
cc.sort()

In [37]:
cc

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [38]:
(20+22)/2

21.0

In [31]:
np.percentile(b, 50)

21.0

In [27]:
np.percentile(b, 90) #90th percentile

36.2

In [40]:
b

array([[ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38],
       [10, 20, 30, 40]])

In [39]:
np.sqrt(b) #square root of all elements

array([[1.41421356, 3.46410162, 4.69041576, 5.65685425],
       [2.        , 3.74165739, 4.89897949, 5.83095189],
       [2.44948974, 4.        , 5.09901951, 6.        ],
       [2.82842712, 4.24264069, 5.29150262, 6.164414  ],
       [3.16227766, 4.47213595, 5.47722558, 6.32455532]])

In [41]:
np.exp(b) #exponentiation with e

array([[7.38905610e+00, 1.62754791e+05, 3.58491285e+09, 7.89629602e+13],
       [5.45981500e+01, 1.20260428e+06, 2.64891221e+10, 5.83461743e+14],
       [4.03428793e+02, 8.88611052e+06, 1.95729609e+11, 4.31123155e+15],
       [2.98095799e+03, 6.56599691e+07, 1.44625706e+12, 3.18559318e+16],
       [2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17]])

In [42]:
np.log(b) #natural logarithm

array([[0.69314718, 2.48490665, 3.09104245, 3.4657359 ],
       [1.38629436, 2.63905733, 3.17805383, 3.52636052],
       [1.79175947, 2.77258872, 3.25809654, 3.58351894],
       [2.07944154, 2.89037176, 3.33220451, 3.63758616],
       [2.30258509, 2.99573227, 3.40119738, 3.68887945]])

In [44]:
c = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
c

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [45]:
np.abs(c) #absolute values of all elements

array([1.7, 1.5, 0.2, 0.2, 1.5, 1.7, 2. ])

In [46]:
d=np.array([1.7, 3.1, 0.2, 4.2, 1.5, 2.7, 5.2 ])

In [47]:
d

array([1.7, 3.1, 0.2, 4.2, 1.5, 2.7, 5.2])

In [48]:
np.ceil(d) #element-wise rounding up

array([2., 4., 1., 5., 2., 3., 6.])

In [49]:
np.floor(d) #element-wise rounding down

array([1., 3., 0., 4., 1., 2., 5.])

In [53]:
np.around([-3.23, -0.76, 1.44, 2.65, ], decimals = 1) #evenly round all elements to the given number of decimals.

array([-3.2, -0.8,  1.4,  2.6])

In [52]:
np.around([-3.26, -0.76, 1.44, 2.65, ], decimals = 1) #evenly round all elements to the given number of decimals.

array([-3.3, -0.8,  1.4,  2.6])

In [55]:
round(3.23,2)

3.23

In [56]:
round(3.23,1)

3.2