In [37]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

In [ ]:
# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default  # fractional step count is allowed 

In [ ]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize

In [ ]:
# Reshape:

# M1
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column

# M2
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [ ]:
# # Transpose

# #Method1
# array.T

# #Method2
# array.transpose()

In [ ]:
#resize()
# It changes the original array directly and does not return a new array

In [38]:
arr=np.arange(1,11)

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
b=arr.reshape(2,5)

In [42]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr.reshape(3,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [ ]:
#resize():- returns a new array with a new shape

In [ ]:
# M1

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr.resize(2,5)

In [47]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
arr.resize(1,10)

In [50]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [51]:
arr.resize(4,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [52]:
arr2=np.arange(1,11)

In [ ]:
# M2

In [55]:
np.resize(arr2,(2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
np.resize(arr,(4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10,  1,  2]])

In [61]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [60]:
np.resize(arr,(2,2))

array([[1, 2],
       [3, 4]])

In [57]:
np.reshape(arr,(4,3))

ValueError: cannot reshape array of size 10 into shape (4,3)

In [62]:
b=np.arange(2,22,2)

In [63]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
b.size

10

In [65]:
b.reshape(2,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [66]:
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
b.resize(2,5)

In [68]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [69]:
import numpy as np

In [75]:
a=np.arange(2,22,2)

In [77]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [78]:
l=[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]

In [79]:
sum=0
for i in l:
    sum=sum+i

In [80]:
sum

110

In [ ]:
#Aggregate functions

In [81]:
a.sum() # #np.sum(data)

110

In [82]:
b.sum()

AttributeError: 'list' object has no attribute 'sum'

In [83]:
np.sum(b)

110

In [84]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
a.min()

2

In [86]:
a.max()

20

In [88]:
a.sum()

110

In [90]:
a.size

10

In [91]:
a.sum()/a.size

11.0

In [92]:
a.mean()

11.0

In [93]:
a.var()  #

33.0

In [94]:
a.std()

5.744562646538029

In [95]:
a.std()*a.std() #var

33.0

In [ ]:
# Homework

In [105]:
arr=np.arange(2,42,2)

In [106]:
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [107]:
arr.size

20

In [108]:
b=arr.reshape(4,5)

In [109]:
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [ ]:
# # Retrive following value from array b
# 1) 14
# 2) 28
# 3) 6
# 4) 34

# 5) 24,26,28

# 6) 14,16
#    24,26

# 7)[22, 24, 26, 28, 30]
#   [32, 34, 36, 38, 40]
    
# 8) 4
#    14
#     24
#     34