### Manipulate arrays

In [78]:
import numpy as np

In [79]:
# np.append(): adds values to the end of an array. It returns a new array
# np.concatenate(): Combines two or more arrays along a specified axis
# np.vstack(): Stacks arrays vertically (row-wise)
# np.hstack(): Stacks arrays horizontally (column-wise)
#  "stack" refers to the operation of joining multiple arrays along a new axis

In [18]:
#append
c=np.arange(1,16).reshape((3,5))
d=np.arange(21,36).reshape((3,5))

In [25]:
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [26]:
print(d)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [21]:
aa=np.append(c,d)

In [24]:
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [23]:
np.append(c,d,axis=0)  #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [27]:
np.append(c,d,axis=1)  #column

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [28]:
# combining
# M1)concatenate
np.concatenate((c,d),axis=0) #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [29]:
np.concatenate((c,d),axis=1) #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [30]:
np.concatenate((c,d))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [31]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
d

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [33]:
# M2)
np.vstack((c,d))  #row axis=0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [34]:
np.hstack((c,d)) #col axis=1

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [35]:
# M3)
np.column_stack((c,d)) #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [36]:
np.row_stack((c,d)) #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [37]:
# M4)
np.r_[c,d] #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [38]:
np.c_[c,d]  #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [42]:
#splitting
a=np.r_[c,d]
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [43]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [44]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [45]:
np.vsplit(a,4)

ValueError: array split does not result in an equal division

In [47]:
a1,b1,c1=22,23,24

In [49]:
print(a1,b1,c1)

22 23 24


In [50]:
a1=(24,25,26)

In [51]:
a1

(24, 25, 26)

In [52]:
a2,b2,c2=a1

In [53]:
print(a2,b2,c2)

24 25 26


In [54]:
22,23,24

(22, 23, 24)

In [46]:
k=np.vsplit(a,3)
k

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [55]:
a1,b1,c1=np.vsplit(a,3) # Split into 3 equally-sized sub-arrays

In [56]:
a1   # unpaking

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [57]:
b1

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])

In [58]:
c1

array([[26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [59]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [65]:
np.hsplit(a,5)

[array([[ 1],
        [ 6],
        [11],
        [21],
        [26],
        [31]]),
 array([[ 2],
        [ 7],
        [12],
        [22],
        [27],
        [32]]),
 array([[ 3],
        [ 8],
        [13],
        [23],
        [28],
        [33]]),
 array([[ 4],
        [ 9],
        [14],
        [24],
        [29],
        [34]]),
 array([[ 5],
        [10],
        [15],
        [25],
        [30],
        [35]])]

In [61]:
np.hsplit(a,2)

ValueError: array split does not result in an equal division

In [60]:
np.hsplit(a,3)

ValueError: array split does not result in an equal division

In [67]:
np.vsplit(a,2)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 array([[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [66]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [68]:
np.vsplit(a,3)

[array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]])]

In [69]:
np.vsplit(a,6)

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]]),
 array([[21, 22, 23, 24, 25]]),
 array([[26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35]])]

In [70]:
np.vsplit(a,4)

ValueError: array split does not result in an equal division

In [ ]:
c

In [ ]:
d

In [ ]:
b=np.c_[c,d] 
b

In [ ]:
np.vsplit(b,3)

In [ ]:
np.hsplit(b,5)

In [ ]:
np.vsplit(b,3)

In [71]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [75]:
arr[arr < 5]

array([1, 2, 3, 4])

In [76]:
arr[~arr < 5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])