In [87]:
import numpy as np  #import numpy

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

In [ ]:
# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default  # fractional step count is allowed 

In [ ]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize

In [ ]:
# Reshape:

In [ ]:
# M1
# np.reshape(data,shape,order(Fill_by))
# shape= (row,col)
# order (Fill_by) "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [88]:
a=np.arange(1,11)

In [89]:
l=list(range(1,11))

In [90]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [91]:
l

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [92]:
np.reshape(a,(2,5),"C")

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [93]:
np.reshape(a,(2,5),"F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [94]:
np.reshape(a,(2,6),"C")

ValueError: cannot reshape array of size 10 into shape (2,6)

In [97]:
np.reshape(l,(2,5),"F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [ ]:
# M2
# Array.reshape(shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [103]:
a.reshape((2,5),order="F")

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [100]:
l.reshape((2,5),order="F")

AttributeError: 'list' object has no attribute 'reshape'

In [104]:
a.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [105]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#Examples

In [106]:
a = np.arange(18).reshape(3,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [108]:
a = np.arange(15).reshape(3,5) #rowwise
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [110]:
a = np.arange(15).reshape((3,5),order="F") #columnwise
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [107]:
a = np.arange(15).reshape(2,7)
print(a)

ValueError: cannot reshape array of size 15 into shape (2,7)

In [111]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [112]:
a = np.arange(16).reshape(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [113]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [114]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [115]:
a.ndim

2

In [116]:
a.size

16

In [117]:
a = a.reshape(2,8) # Reshape 2x8
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [118]:
a = a.reshape(8,2) # Reshape 2x8
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [119]:
a = a.reshape(4,4) 
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [120]:
a = a.reshape(16,1) 
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [121]:
a = a.reshape(1,16) 
print(a)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]


In [ ]:
# Transpose

In [122]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [123]:
#Method1
arr_transpose  = a.T
arr_transpose

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [125]:
a.T.T.T.T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [124]:
#Method2
transpose  = a.transpose()
print(transpose)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
