In [20]:
import numpy as np  #import numpy

In [21]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

In [22]:
# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default  # fractional step count is allowed 

In [23]:
#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize

In [24]:
# Creating 1D array: Excel (perticular column only)

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [25]:
# Creating  2D array: Excel (Row and columns)

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Creating  3D array: Image

arr3d = np.array([[[1, 2, 3], [4, 5, 6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]]])

In [31]:
aa=[1,2,3,[1,2,3,[1,22,3]],1,2,3]
#         3     3

In [32]:
aa[3][3][1]

22

In [27]:
np.array([
    [
        [1, 2, 3],
           [4, 5, 6],
           [4, 5, 6]
    ],
          
          [
              [1, 2, 3],
           [4, 5, 6],
           [4, 5, 6]
          ]
]).shape

(2, 3, 3)

In [33]:
a=np.arange(27)
b=np.reshape(a,(3,3,3),"C")
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
b.shape

(3, 3, 3)

In [57]:
a=np.arange(24)

In [58]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
a.size

24

In [60]:
4*2*3

24

In [61]:
b=np.reshape(a,(4,2,3),"C")

In [62]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [63]:
b=np.reshape(a,(2,3),"C") # shape multiplication not match with input size

ValueError: cannot reshape array of size 24 into shape (2,3)

In [64]:
np.reshape(a,(6,4)) # shape multiplication match with input size

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [65]:
np.reshape(a,(6,4),"F")

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [38]:
b.shape # 3D Array
        # Shape (Frame, Row, Columns)

(4, 2, 3)

In [40]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2d.shape #array shape :tuple representing the dimensions of the array

(2, 3)

In [ ]:
arr3d.shape

In [41]:
arr2d.ndim  # dimension

2

In [42]:
b.ndim

3

In [43]:
arr2d.size  # no. arry elements

6

In [44]:
b.size

24

In [45]:
arr2d.dtype #data type of array element (int,float,complex,bool,string,object)

dtype('int32')

In [ ]:
# Reshape:

In [ ]:
# np.reshape(data,shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [46]:
a=np.arange(1,21,2)

In [47]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [48]:
a.size

10

In [49]:
a.ndim

1

In [50]:
a.shape

(10,)

In [51]:
a.dtype

dtype('int32')

In [52]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [53]:
# M1 ==> Prefere if input dsts id not array
np.reshape(a,(2,5),"C")

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [56]:
np.reshape(a,(2,5),"F")

array([[ 1,  5,  9, 13, 17],
       [ 3,  7, 11, 15, 19]])

In [55]:
a.size

10

In [54]:
np.reshape(a,(2,6),"C")

ValueError: cannot reshape array of size 10 into shape (2,6)