### Mathematical functions

In [1]:
import numpy as np

In [2]:
b=np.arange(2,41,2).reshape((5,4),order="F")

In [3]:
np.around([-3.23, -0.76, 1.44, 2.65, ], decimals = 1) #evenly round all elements to the given number of decimals.

array([-3.2, -0.8,  1.4,  2.6])

In [4]:
np.around([-3.26, -0.76, 1.44, 2.65, ], decimals = 1) #evenly round all elements to the given number of decimals.

array([-3.3, -0.8,  1.4,  2.6])

In [5]:
round(3.23,2)

3.23

In [6]:
round(3.26,1)

3.3

### Matrix

In [ ]:
# Element-wise operations:
# Addition: np.add()
# Subtraction: np.subtract()
# Division: np.divide()
# Multiplication: np.multiply()

In [7]:
# Define two matrices to multiply
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 7]])

In [8]:
print(matrix1)

[[1 2]
 [3 4]]


In [9]:
print(matrix2)

[[5 6]
 [7 7]]


In [ ]:
# Addition:

In [10]:
matrix1 + matrix2

array([[ 6,  8],
       [10, 11]])

In [11]:
np.add(matrix1,matrix2)

array([[ 6,  8],
       [10, 11]])

In [ ]:
# Subtraction:

In [12]:
matrix1 - matrix2

array([[-4, -4],
       [-4, -3]])

In [13]:
np.subtract(matrix1,matrix2)

array([[-4, -4],
       [-4, -3]])

In [14]:
np.subtract(matrix2,matrix1)

array([[4, 4],
       [4, 3]])

In [ ]:
# Division:

In [15]:
matrix1 / matrix2

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [16]:
np.divide(matrix1,matrix2)

array([[0.2       , 0.33333333],
       [0.42857143, 0.57142857]])

In [19]:
matrix1

array([[1, 2],
       [3, 4]])

In [20]:
matrix2

array([[5, 6],
       [7, 7]])

In [ ]:
# Multiplication:

In [17]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 28]])

In [18]:
np.multiply(matrix1,matrix2)

array([[ 5, 12],
       [21, 28]])

### Linear Algebra

In [ ]:
# np.dot(): Computes the dot product of two arrays. 
# np.linalg.inv(): Computes the inverse of a matrix.
# np.linalg.det(): Computes the determinant of a matrix.
# np.linalg.eig(): Computes the eigenvalues and right eigenvectors of a square array.

In [21]:
# Method 1: Using np.dot()
result1 = np.dot(matrix1, matrix2)
print(result1)

[[19 20]
 [43 46]]


In [22]:
# Method 2: Using @ operator
result2 = matrix1 @ matrix2
print(result2)

[[19 20]
 [43 46]]


In [23]:
# Compute the determinant
matrix = np.array([[1, 2], [3, 4]])

In [24]:
matrix

array([[1, 2],
       [3, 4]])

In [26]:
det = np.linalg.det(matrix)
print(round(det,2))

-2.0


In [27]:
# calculate the inverse
matrix_inv = np.linalg.inv(matrix)

print(matrix_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
#cross check     
matrix @ matrix_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [31]:
np.around(matrix @ matrix_inv)

array([[1., 0.],
       [0., 1.]])

In [32]:
np.linalg.eig(matrix)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
#Exercise

In [ ]:
#Create array values and practice following examples
arr=np.arange(10).reshape(5,2)

In [ ]:
# Finding the mean of a NumPy array:

mean_val = np.mean(arr)
mean_val

In [ ]:
# Finding the median of a NumPy array:

median_val = np.median(arr)
median_val

In [ ]:
# Finding the standard deviation of a NumPy array:

std_val = np.std(arr)
std_val

In [ ]:
var_val = np.var(arr)
var_val

In [ ]:
# Performing element-wise operations on NumPy arrays:

arr_squared = arr ** 2
arr_squared

In [ ]:
# create an array of data
data = np.arange(100)

# calculate the mean
mean = np.mean(data)
print("Mean:", mean)

# calculate the median
median = np.median(data)
print("Median:", median)

# calculate the variance
variance = np.var(data)
print("Variance:", variance)

# calculate the standard deviation
std_dev = np.std(data)
print("Standard deviation:", std_dev)

# calculate the minimum and maximum values
minimum = np.min(data)
maximum = np.max(data)
print("Minimum:", minimum)
print("Maximum:", maximum)